version: '3.8'

services:
  db:
    image: postgres:15.5-alpine
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=devpass
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./configuration/src/main/resources/jdbc/schema.sql:/docker-entrypoint-initdb.d/init.sql
