name: Tests Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Unit Tests
        run: make unit-tests

      - name: Integration Tests
        run: make integration-tests

      - name: e2e Tests
        run: make e2e-tests
